// القيم الافتراضية لمحتوى الصفحة الرئيسية — مصدر واحد يستخدمه الموقع واللوحة.
export const HOME_DEFAULTS: Record<string, any> = {
  badge_ar: "فريق كله دكاترة بخبرة في الديجيتال ماركتنج",
  badge_en: "A medical team with digital marketing expertise",
  hero_title_ar:
    "اليوم لا تحتاج ظهورًا رقميًا فقط، بل ظهور احترافي يميزك بين منافسيك",
  hero_title_en:
    "Today you don't just need a digital presence — you need a professional presence that sets you apart from competitors.",
  hero_subtitle_ar:
    "فريق MDink Solutions للتسويق الطبي للعيادات والمستشفيات كله دكاترة بخبرة في الديجتال ماركتنج",
  hero_subtitle_en:
    "The MDink Solutions medical-marketing team for clinics and hospitals is made up of doctors experienced in digital marketing.",
  primary_cta_ar: "ابدأ موقعك الآن",
  primary_cta_en: "Start your website",
  secondary_cta_ar: "شاهد خدماتنا",
  secondary_cta_en: "View services",
  trust_ar: ["تسليم في 25 يوم", "دعم متواصل", "ضمان الجودة"],
  trust_en: ["25-day delivery", "Continuous support", "Quality assurance"],
  preview_doctor_ar: "عيادتي",
  preview_doctor_en: "Eyadaty",
  preview_specialty_ar: "All Women Health Services In One Place — Eyadaty",
  preview_specialty_en: "All Women Health Services In One Place — Eyadaty",
  preview_label_ar: "معاينة موقع الطبيب",
  preview_label_en: "Doctor site preview",
  preview_url: "3eyadaty-eg.com",
  preview_link: "https://3eyadaty-eg.com/",
  published_label_ar: "منشور",
  published_label_en: "Published",
  dashboard_card_json: [
    { label_ar: "زائر شهريًا", label_en: "Monthly visitors", value: "18,500", icon: "Users" },
    { label_ar: "حجز شهريًا", label_en: "Monthly bookings", value: "420", icon: "CalendarCheck" },
    { label_ar: "نمو التفاعل", label_en: "Engagement growth", value: "+38%", icon: "TrendingUp" },
    { label_ar: "حملات نشطة", label_en: "Active campaigns", value: "6", icon: "Megaphone" },
  ],
  stats_json: [
    { value: "+50", label_ar: "طبيب وعيادة", label_en: "Doctors and clinics" },
    { value: "+120", label_ar: "حملة إعلانية", label_en: "Ad campaigns" },
    { value: "+10", label_ar: "تخصصات طبية", label_en: "Medical specialties" },
    { value: "98%", label_ar: "رضا العملاء", label_en: "Client satisfaction" },
  ],
  services_title_ar: "خدمات MDink Solutions الكاملة",
  services_title_en: "Complete MDink Solutions Services",
  services_intro_ar: "كل ما يحتاجه طبيبك للوصول للريادة الرقمية في مكان واحد.",
  services_intro_en: "Everything a medical brand needs to grow digitally in one place.",
  services_json: [
    {
      title_ar: "تصميم مواقع طبية",
      title_en: "Medical Websites",
      desc_ar: "موقع احترافي خاص بكل طبيب مهيأ للسيو والموبايل.",
      desc_en: "Professional doctor-owned websites built for SEO and mobile.",
      icon: "Globe",
    },
    {
      title_ar: "سيو طبي متقدم",
      title_en: "Medical SEO",
      desc_ar: "Schema.org + صفحات تخصصات تجذب بحث المرضى من جوجل.",
      desc_en: "Schema.org and specialty pages that attract patients from Google.",
      icon: "TrendingUp",
    },
    {
      title_ar: "إعلانات PPC",
      title_en: "PPC Ads",
      desc_ar: "حملات Meta و Google Ads بأعلى عائد استثمار.",
      desc_en: "Meta and Google campaigns focused on return on investment.",
      icon: "Megaphone",
    },
    {
      title_ar: "إدارة سوشيال ميديا",
      title_en: "Social Media",
      desc_ar: "تقويم محتوى شهري كامل + تصميم + جدولة + متابعة.",
      desc_en: "Monthly content calendar, design, scheduling, and follow-up.",
      icon: "Sparkles",
    },
    {
      title_ar: "هوية بصرية",
      title_en: "Brand Identity",
      desc_ar: "لوجو + هوية كاملة تناسب تخصص الطبيب.",
      desc_en: "Logo and complete identity aligned with the medical specialty.",
      icon: "ShieldCheck",
    },
    {
      title_ar: "لوحة تحكم خاصة بك",
      title_en: "Private Dashboard",
      desc_ar: "تحكم كامل بالموقع، الخدمات، الصور، والمحتوى.",
      desc_en: "Manage website content, services, images, and updates.",
      icon: "LayoutDashboard",
    },
  ],
  why_title_ar: "ليه تختار MDink Solutions",
  why_title_en: "Why Choose MDink Solutions",
  why_intro_ar:
    "في سوق مزدحم بالوكالات، نقدّم تركيبة فريدة لا يقدّمها أي منافس: منصة مملوكة لك بالكامل + خدمة تسويقية متكاملة — لكل طبيب، عيادة، أو مركز طبي.",
  why_intro_en:
    "We combine a fully-owned digital platform with integrated marketing services for doctors, clinics, and medical centers — not a temporary campaign only.",
  advantages_json: [
    {
      ar: "منصة مملوكة لك بالكامل — طبيبًا كنت أو عيادة أو مركزًا طبيًا — لا مجرد خدمة تسويقية مؤقتة",
      en: "A platform fully owned by you — doctor, clinic, or medical center — not a temporary agency service",
    },
    {
      ar: "لوحة تحكم سهلة تحرر محتواك بنفسك بدون مبرمج",
      en: "A simple dashboard to edit content without a developer",
    },
    {
      ar: "تقارير أداء مباشرة من اللوحة بدل انتظار الوكالة",
      en: "Direct performance reports from the dashboard",
    },
    {
      ar: "تصميم بصري مخصص لكل تخصص — لا قوالب عامة",
      en: "Specialty-based visual design, not generic templates",
    },
    {
      ar: "ربط مباشر بواتساب وحجز فوري لتحويل الزائر لعميل",
      en: "WhatsApp and fast contact flows that convert visitors",
    },
  ],
  talk_ar: "تحدّث معنا الآن",
  talk_en: "Talk to us now",
  system_label_ar: "منظومة متكاملة",
  system_label_en: "Integrated system",
  system_title_ar: "منظومة رقمية متكاملة للقطاع الطبي",
  system_title_en: "An Integrated Digital Ecosystem for Healthcare",
  system_intro_ar: "موقع احترافي، لوحات تحكم، إدارة محتوى، وتقويم تسويقي — جاهزة للإطلاق والنمو.",
  system_intro_en:
    "A professional website, dashboards, content management, and a marketing calendar — ready to launch and grow.",
  system_items_json: [
    { ar: "موقع MDink Solutions الرئيسي لإدارة حضورك الرقمي", en: "MDink Solutions's main website to manage your digital presence" },
    {
      ar: "مواقع مخصصة للأطباء والعيادات والمراكز الطبية",
      en: "Dedicated websites for doctors, clinics, and medical centers",
    },
    { ar: "لوحة تحكم سهلة لتعديل الخدمات والمحتوى", en: "An easy dashboard to edit services and content" },
    { ar: "لوحة إدارة للمتابعة والتقارير والطلبات", en: "A management dashboard for tracking, reports, and requests" },
    { ar: "تقويم محتوى منظم للسوشيال ميديا", en: "An organized social media content calendar" },
  ],
  cta_title_ar: "جاهز تبني موقعك الطبي الاحترافي؟",
  cta_title_en: "Ready to build your professional medical website?",
  cta_text_ar: "احجز استشارة مجانية الآن وابدأ رحلتك للريادة الرقمية في تخصصك.",
  cta_text_en: "Book a free consultation and start building your digital leadership.",
  cta_primary_ar: "احجز استشارة مجانية",
  cta_primary_en: "Book a free consultation",
  cta_secondary_ar: "اعرف أكثر",
  cta_secondary_en: "Learn more",
  hero_bg_image: "",
  preview_card_image: "",
  sections_order: ["hero", "stats", "services", "why", "system", "cta"],
  sections_hidden: [],
};
